# Radio channel used for robot programming
ROBOT_CHANNEL = 126
# Port for radio interface
ROBOT_PORT = COM3

# List of base firmware files
BASE_FIRMWARE_C = $(SRC_SUBDIR)uartISR.c $(SRC_SUBDIR)armVIC.c $(SRC_SUBDIR)radio.c $(SRC_SUBDIR)LPC_CANAll.c $(SRC_SUBDIR)sysTime.c $(SRC_SUBDIR)uart.c $(SRC_SUBDIR)i2c.c $(SRC_SUBDIR)can.c $(SRC_SUBDIR)hardware.c $(SRC_SUBDIR)timerISR.c $(SRC_SUBDIR)adc.c $(SRC_SUBDIR)printf.c $(SRC_SUBDIR)utils.c $(SRC_SUBDIR)lutmath.c $(SRC_SUBDIR)registers.c $(SRC_SUBDIR)robot.c 
BASE_FIRMWARE_S = $(SRC_SUBDIR)crt0.S
